services:
  client-react:
    build:
      context: ./client-react/
      dockerfile: Dockerfile
    init: true
    volumes:
      - type: bind
        source: ./client-react/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./client-react/vite.config.docker.js
        target: /usr/src/app/vite.config.js
    command: ["npm", "run", "dev"]
    networks:
      - frontend
    ports:
      - "5173:5173"

  api-node:
    build:
      context: ./api-node/
      dockerfile: Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./api-node/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - backend
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  frontend:
  backend:
